<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Via.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\sav_icon.png" />
    <None Remove="Assets\sav_logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\sav_icon.png" />
    <Resource Include="Assets\sav_logo.png" />
  </ItemGroup>

</Project>
